baseURL = 'https://example.org/'
languageCode = 'en-gb'
title = 'BTD6 Mastery Tips & Tricks'

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['$$', '$$']]
[params]
  math = true